### ISSUE TITLE
Error:Failed to resolve: com.google.android.agera:rvadapter:1.2.0-beta2

### ISSUE THREAD

**Issue by captain-miao** [google/agera#102]
There is only source.jar.

https://bintray.com/ernstsson/Agera/agera#files/com/google/android/agera/rvadapter/1.2.0-beta2

also:

Failed to resolve: com.google.android.agera:rvdatabinding:1.2.0-beta2

**Comment by drakeet** [comment]
+1

**Comment by ernstsson** [comment]
How odd. Re-exported, try again

**Comment by captain-miao** [comment]
It's ok.

**Comment by ernstsson** [comment]
Great! sorry about that.
