### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by jacekTymicki** [google/agera#112]
_Hey,
I have checked out master branch and compilation attempt finishes with following error:_
Error:A problem occurred configuring project ':extensions:rvdatabinding'.
> Could not find support-v4.jar (com.android.support:support-v4:24.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-v4/24.1.1/support-v4-24.1.1.jar

_Change of settings.gradle from
gradle.ext.buildToolsVersion = '24.0.0'
gradle.ext.supportLibraryVersion = '24.1.1'
to
gradle.ext.buildToolsVersion = '24.0.2'
gradle.ext.supportLibraryVersion = '24.2.0'_
_fixes compilation error but when I try to run testapp I have following error:_

> AGPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;","sources":[{}],"original":"UNEXPECTED TOP-LEVEL EXCEPTION:\ncom.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;\n\tat com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)\n\tat com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)\n\tat com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)\n\tat com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)\n\tat com.android.dx.merge.DexMerger.merge(DexMerger.java:188)\n\tat com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)\n\tat com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)\n\tat com.android.dx.command.dexer.Main.run(Main.java:277)\n\tat com.android.dx.command.dexer.Main.main(Main.java:245)\n\tat com.android.dx.command.Main.main(Main.java:106)\n","tool":"Dex"}
> 
> :testapp:transformClassesWithDexForDebug FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':testapp:transformClassesWithDexForDebug'.
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Android\Android Studio\jre\bin\java.exe'' finished with non-zero exit value 2
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 44.702 secs

**Comment by ernstsson** [comment]
Support libraries (24.1.1 as well as the others) are added though the SDK manager. Can you check that you have it added properly through there?
