### ISSUE TITLE
[question] Push Event on a high speed frequency, Pull Data will too busy to attend to all

### ISSUE THREAD

**Issue by sfcecy7i** [google/agera#164]
When the Repository changes very fast, how to get every change? Custom Repository?
```
        val repo = Repositories.mutableRepository("")
        repo.addUpdatable {
            SystemClock.sleep(10L)
            Log.d("TEST", repo.get())
        }
        thread {
            while (true) {
                SystemClock.sleep(1L)
                repo.accept(System.currentTimeMillis().toString())
            }
        }
```

**Comment by ernstsson** [comment]
The mutable repository drops events by design. Possibly the `Reservoir` would do what you want, I'll let @maxtroy comment on this too

**Comment by sfcecy7i** [comment]
https://github.com/google/agera/wiki/Reservoirs-and-parallelism
I should have got the answer in this page of the wiki.
Certainly I should read the wiki again.
