### ISSUE TITLE
Could not find dependency "com.google.android.agera:agera:1.4.0"

### ISSUE THREAD

**Issue by AbhilashG001** [google/agera#171]
**Summary:**

I get the following error message while building the project - ```Could not find dependency "com.google.android.agera:agera:1.4.0```. The SDK Manager already has all the updates installed and there are no pending updates. Also, Android Studio is currently running on the latest stable build. 

**Steps to reproduce the issue:**

1. Open Android Studio 
1. Add the follwoing dependency to your project. 
```implementation 'com.google.android.agera:agera:1.4.0'```
1. Build the project

**Expected Behavior:**

The project should build without any errors.

**Observed Behavior:**

The project build fails with the following error message - ```Could not find dependency "com.google.android.agera:agera:1.4.0"```

**Android Studio Version:**

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Screenshot:**

![agera-dependency-issue](https://user-images.githubusercontent.com/20839661/49733539-cdf62a00-fca7-11e8-837d-98c649ec6531.JPG)

**Comment by ghost** [comment]
Have you added jcenter() under repositories too, or just using something local and/or mavenCentral()?Agera is only published to jcenter

**Comment by AbhilashG001** [comment]
Hello @ernstsson,

Thank you so much for your reply.

Yes, I have jcenter() under repositories, here is my [```build.gradle(project)```](https://gist.github.com/AbhilashG97/ed8915f8aebfd404ba136b1cfe5b92ef) and [```build.gradle(app)```](https://gist.github.com/AbhilashG97/e83584398ea09157620f80f49badab96) file.

Am I doing something wrong?

**Comment by silk** [comment]
Agera seems to be currently missing from jcenter repository.
Or am I wrong?

https://jcenter.bintray.com/com/google/android/ doesn't have agera under it.

**Comment by ghost** [comment]
Looks like it suddenly went missing from jcenter the other day, no idea why. Added it back now, could you try again?

**Comment by AbhilashG001** [comment]
Hello @ernstsson, 

Everything works perfectly fine now. Thank you so much.

**Comment by ghost** [comment]
Is there any other repository which we could use instead of `jcenter()`? As it's going to be closed as I know
