### ISSUE TITLE
Why HTTPUrlConnection and not okhttp or even retrofit ?

### ISSUE THREAD

**Issue by stephanenicolas** [google/agera#22]
It looks like there are more cutting edge alternatives than HTTPUrlConnection for network.

It seems to me that it would be more valuable at some point for Google to properly package volley + retrofit support and make it the official network layer of Android than adding one more library not linked with the rest and the best practices on the platform..

Otherwise, that's an interesting project.

**Comment by shareme** [comment]
maybe there are some not released extensions addressing this point?

**Comment by ernstsson** [comment]
The extensions are more to be considered as fully functional sample extension libraries at this point. I can definitely see extensions of the kind you're referring to (although there is no immediate need for these specific ones by our own projects at the moment). Anything providing a synchronous interface is easily called from an Agera Function (or even a Supplier in some cases).
HTTPUrlConnection (as well as SQLiteDatabase) makes for a good sample extension, since it is part of the platform and no additional dependencies are needed.

**Comment by hangduykhiem** [comment]
One thing about HTTPUrlConnection made it not very newbie-friendly was the implementation with AsycnTask. As @ernstsson just said: 
> Anything providing a synchronous interface is easily called from an Agera Function 
So it should be no harder than implementing the Retrofit or Volley. For some projects it would also be awesome to go fully native.

That being said, old benchmark said that Retrofit was performing better than HTTPUrlConnection, as well as having that auto-caching mechanism. I would really like to see how the Agera with HTTPUrlConnection perform, but I would not bet too much on them.

**Comment by joetimmins** [comment]
As of 4.4 HttpUrlConnection on Android uses OkHttp under the hood anyway. I'd be interested to see if any benchmarks showing Retrofit as faster than HttpUrlConnection still hold true.

https://twitter.com/jakewharton/status/482563299511250944
https://android.googlesource.com/platform/external/okhttp/+/master

**Comment by sungerk** [comment]
how to send a post request with parameter ？ i think the net module is too young

**Comment by ernstsson** [comment]
Are you referring to URL parameters? The URL in the request is a simple `String`. You can add parameters either though direct string concatenation, or using Android classes like `Uri` to create the `String`.
Still, an interesting idea, letting the actual `HttpRequest` compiler add parameters directly.

**Comment by sungerk** [comment]
i know how to achieved it, but as this issue , i think  okhttp or retrofit is good enough

**Comment by sungerk** [comment]
@ernstsson  it has so many final and private class !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
