### ISSUE TITLE
A typo in one of the wiki pages? 

### ISSUE THREAD

**Issue by xavieryao** [google/agera#23]
In one of the wiki pages, [Incrementally-Agerifying-legacy-code](https://github.com/google/agera/wiki/Incrementally-Agerifying-legacy-code), there seems to be a typing mistake. In the sample code of *Exposing synchronous operations as repositories*, did you mean `Repositories.repositoryWithInitialValue(Result<ResponseBlob>.absent())` rather than the expression        `Repositories.repositoryWithInitialValue(Result.<ResponseBlob>absent())` ?

**Comment by maxtroy** [comment]
`ClassName.<TypeParam>staticMethodName()` is the right Java syntax :)

**Comment by xavieryao** [comment]
I sincerely apologize.
