### ISSUE TITLE
translation of wiki for Korean

### ISSUE THREAD

**Issue by ZeroBrain** [google/agera#33]
hi. I'm GDE of South Korea.
recently, I saw this repository. I was interested in Reactive Android.
so I decided that I would translate to Korean.

this link is output of translation.
: https://github.com/ZeroBrain/agera-wiki-kr/wiki

I worked with some GDGs for translation.

I appreciate that I can do that.

Thank you so much for great job that making agera.

**Comment by JoseAlcerreca** [comment]
Hi! Wow, great job guys!

We're still modifying the wiki so let's get back to it when we release the stable version and we'll link to it from the official one.

Thanks!

**Comment by ZeroBrain** [comment]
Thanks for your reply.

I really hope to release stable version soon. :)
