### ISSUE TITLE
what the f*** is this

### ISSUE THREAD

**Issue by AndreiD** [google/agera#37]
why the f**** you, GOOGLE< a TITAN and AN EXAMPLE TO ALL OTHER, make a library without a description, without some more solid documentation ??? you you even publish this without taking a little time to talk more about it, give examples etc. etc. 

WHAT THE F**** can I understand from you bitmap example

WHY you took the time to create a LOGO for this, and not take time to write some documentation  ?????????????????????????????

**Comment by hangduykhiem** [comment]
Did you even read the README.md? There was this link. https://github.com/google/agera/wiki.

Don't show this side of you on the net, dude. These things stick on your record.

**Comment by AndreiD** [comment]
We are all grateful for your library, but what you don't get is that you cannot throw things without providing some more explanation for them.  Your experience in publishing open source is 0. I suggest you have a talk with those guys at squareup and see how they publish their open source and how they create their documentation.   Me and other developers would very much want to use your library but without banging our heads in the wall trying to make it work, nor digging though github issues just because you're too lazy to improve the documentation
