### ISSUE TITLE
[Question] How to do disable the update event when  Repository.addUpdatable.

### ISSUE THREAD

**Issue by captain-miao** [google/agera#52]
When Repository.addUpdatable(), will trigger update event. 
How to disable the update event when  addUpdatable().

```
 @Override
  protected void observableActivated() {
    eventSource.addUpdatable(this);
    maybeStartFlow();
  }

  @Override
  protected void observableDeactivated() {
    eventSource.removeUpdatable(this);
    maybeCancelFlow(deactivationConfig, false);
  }
```

**Comment by maxtroy** [comment]
If the operators behind a compiled repository are designed in a way that the new result will be the same as the current result, then (by default) the compiled repository will not notify any client updatable.
